### ISSUE TITLE
Story Board needs to be Finished

### ISSUE THREAD

**Issue by Toltar** [cr4zyc0dy/harambestudios#2]
Will post images in a bit

**Comment by cr4zyc0dy** [comment]
Still waiting on images..

**Comment by LeviDooley** [comment]
Here's one.

![storyboard coin flip - better top down](https://cloud.githubusercontent.com/assets/18010173/18863308/41c8e02a-8456-11e6-8687-29d9d6dafe38.png)

**Comment by LeviDooley** [comment]
The stick figure version.
![storyboard coin flip](https://cloud.githubusercontent.com/assets/18010173/18893244/a474442c-84d2-11e6-9211-16f84bc12114.png)
